#!/usr/bin/bash
#Author dev@Borodin-Atamanov.ru
#License: MIT
#This file contains automaticaly generated variables, what using in target system in every run

#load functions and default variables
#source "/home/i/bin/dzintara/index.sh" fun
#this script will load all dzintara functions, variables, etc

#One can find generated variables below

#this script generated by install_autorun_script task from Dzintara


